version: '3.9'

services:
  web:
    build: ./app
    container_name: django_app
    working_dir: /app
    command: >
      sh -c "
        until nc -z $DB_HOST $DB_PORT; do
          echo 'Waiting for Postgres...';
          sleep 1;
        done;
        python manage.py migrate &&
        gunicorn django_hello.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/staticfiles
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
